# Generated by Django 5.2.5 on 2025-08-10 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_bundle_telco_databundleorder_payment_bundle_telco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(choices=[('mtnup2u', 'MTNUP2U'), ('telecel', 'Telecel'), ('atishare', 'AT-iShare')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='telco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.telco'),
        ),
        migrations.AlterField(
            model_name='databundleorder',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.bundle'),
        ),
        migrations.AlterField(
            model_name='databundleorder',
            name='telco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.telco'),
        ),
        migrations.AlterField(
            model_name='databundleorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='system.databundleorder'),
        ),
    ]
