# Generated by Django 5.2.5 on 2025-08-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_bundle_name_alter_bundle_telco_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'ordering': ['name', 'size_mb']},
        ),
    ]
