# Generated by Django 5.2.5 on 2025-08-10 13:49

import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_bundle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'ordering': ['telco__name', 'size_mb']},
        ),
        migrations.AddField(
            model_name='bundle',
            name='is_instock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='is_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='id',
            field=models.CharField(default=system.models.generate_bundle_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=system.models.generate_user_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='databundleorder',
            name='id',
            field=models.CharField(default=system.models.generate_order_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(default=system.models.generate_payment_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telco',
            name='id',
            field=models.CharField(default=system.models.generate_telco_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='bundle',
            unique_together={('telco', 'size_mb', 'name')},
        ),
    ]
