# Generated by Django 5.2.5 on 2025-08-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_bundle_options_bundle_is_instock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telco',
            name='is_instock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telco',
            name='is_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telco',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
