# Generated by Django 5.2.5 on 2025-08-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
