# Generated by Django 5.2.5 on 2025-08-11 12:50

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.CharField(default=authentication.models.generate_audit_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='id',
            field=models.CharField(default=authentication.models.generate_bundle_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=authentication.models.generate_user_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='databundleorder',
            name='id',
            field=models.CharField(default=authentication.models.generate_order_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=authentication.models.generate_otp_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(default=authentication.models.generate_payment_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='telco',
            name='id',
            field=models.CharField(default=authentication.models.generate_telco_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
