# Generated by Django 5.2.5 on 2025-08-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_auditlog_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, default='unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_agent',
            field=models.TextField(blank=True, default='unknown'),
            preserve_default=False,
        ),
    ]
