# Generated by Django 5.2.5 on 2025-08-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_auditlog_user_agent_alter_payment_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='databundleorder',
            name='datamart_order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='databundleorder',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
