# Generated by Django 5.2.5 on 2025-08-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_databundleorder_datamart_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databundleorder',
            name='datamart_order_id',
        ),
        migrations.AddField(
            model_name='databundleorder',
            name='provider_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='databundleorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
