# Generated by Django 5.2.5 on 2025-08-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='is_agent_bundle',
            field=models.BooleanField(default=False),
        ),
    ]
