# Generated by Django 5.2.5 on 2025-08-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_bundle_is_agent_bundle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bundle',
            unique_together={('telco', 'size_mb', 'name', 'is_agent_bundle')},
        ),
    ]
