# Generated by Django 5.2.5 on 2025-08-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_bundle_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_created_failed', 'User Creation Failed'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('email_verified', 'Email Verified'), ('email_verification_error', 'Email Verification Error'), ('otp_generated', 'OTP Generated'), ('otp_verified', 'OTP Verified'), ('otp_verification_failed', 'OTP Verification Failed'), ('otp_resent', 'OTP Resent'), ('otp_resend_failed', 'OTP Resend Failed'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('order_created', 'Order Created'), ('payment_made', 'Payment Made')], max_length=30),
        ),
    ]
